FROM registry-intl.ap-southeast-1.aliyuncs.com/measiagroup/jenkins-slaves:lts

ENV DOCKER_VERSION=17.06.2 \
    DOCKER_COMPOSE_VERSION=1.20.0 \
    DOCKER_COMPOSE_MD5=80b6349a390ef3a58250f892fb0cb3c1 \
    CLAIR_SCANNER_VERSION=v8

RUN apt-get update 